version: '3.5'
services:
  fluentbit:
    container_name: fluentbit
    image: fluent/fluent-bit:1.9.0
    build:
      context: ./fluent-bit
    networks:
      - web_network
      - db_network
    ports:
      - "24224:24224"
      - "24224:24224/udp"
  db:
    container_name: db
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: pass
      POSTGRES_USER: appseed
      POSTGRES_DB: appseed-flask
    ports:
      - 5432:5432
    networks:
      - db_network
    depends_on:
      - fluentbit
    logging:
      driver: "fluentd"
      options:
        tag: db
  app_server:
    container_name: app_server
    restart: always
    env_file: .env
    build: .
    networks:
      - db_network
      - web_network
    depends_on:
      - fluentbit
      - db
    logging:
      driver: "fluentd"
      options:
        tag: app_server
  web_server:
    container_name: web_server
    restart: always
    image: "nginx:latest"
    build:
      context: ./nginx
    ports:
      - "80:80"
    networks:
      - web_network
    depends_on:
      - fluentbit
      - app_server
    logging:
      driver: "fluentd"
      options:
        tag: web_server
networks:
  db_network:
    driver: bridge
  web_network:
    driver: bridge
