version: '3.5'
services:
  fluentbit:
    container_name: fluentbit
    image: fluent/fluent-bit:1.9.0
    build:
      context: ./fluent-bit
    networks:
      - web_network
    ports:
      - "24224:24224"
      - "24224:24224/udp"
  app_server:
    container_name: app_server
    restart: always
    env_file: .env
    build: .
    networks:
      - db_network
      - web_network
    depends_on:
      - fluentbit
    logging:
      driver: "fluentd"
      options:
        tag: app-server
  web_server:
    container_name: web_server
    restart: always
    image: "nginx:latest"
    build:
      context: ./nginx
    ports:
      - "80:80"
    networks:
      - web_network
    depends_on:
      - fluentbit
      - app_server
    logging:
      driver: "fluentd"
      options:
        tag: web-server

networks:
  db_network:
    driver: bridge
  web_network:
    driver: bridge
